export const certificates = [
  {
    title: "NDG Linux Unhatched",
    issuer: "Cisco / NDG",
    date: "2024",
    file: "/certificates/ndg_linux_unhatched.pdf",
    category: "Linux",
  },
  {
    title: "React",
    issuer: "Coursera",
    date: "2024",
    file: "/certificates/react.pdf",
    category: "Frontend",
  },
  {
    title: "Django Web Development",
    issuer: "Coursera",
    date: "2024",
    file: "/certificates/django_coursera.pdf",
    category: "Backend",
  },
  {
    title: "Introduction to Cybersecurity",
    issuer: "Cisco",
    date: "2024",
    file: "/certificates/intro_cybersecurity.pdf",
    category: "Security",
  },
  {
    title: "Introduction to Data Science",
    issuer: "Cisco",
    date: "2024",
    file: "/certificates/intro_data_science.pdf",
    category: "Data",
  },
  {
    title: "CCNA Enterprise Networking",
    issuer: "Cisco",
    date: "2024",
    file: "/certificates/ccna_enterprise_networking.pdf",
    category: "Networking",
  },
  {
    title: "CCNA Switching Routing Wireless",
    issuer: "Cisco",
    date: "2024",
    file: "/certificates/ccna_switching_routing_wireless.pdf",
    category: "Networking",
  },
  {
    title: "Network Security",
    issuer: "Cisco",
    date: "2024",
    file: "/certificates/network_security.pdf",
    category: "Security",
  },
  {
    title: "Business Intelligence",
    issuer: "Tecnológico",
    date: "2024",
    file: "/certificates/business_intelligence.pdf",
    category: "Data",
  },
];