export const CONTACT_CONFIG = {
    email: "anahydlira@gmail.com",
    whatsapp: "4492238799",
    linkedin: "https://www.linkedin.com/in/anahi-lozano-de-lira-a4213a187/?skipRedirect=true"
};

export const translations = {
    es: {
        nav_home: 'KERNEL',
        nav_about: 'BIO',
        nav_exp: 'LOGS',
        nav_projects: 'CORE',
        nav_certs: 'HASH',
        nav_contact: 'IO',
        hero_status: 'RUNLEVEL_5: ACTIVO',
        hero_title: 'ROOT@USER:',
        hero_role: 'SOFTWARE DEVELOPER // FULL STACK // MOBILE // SAP',
        hero_desc: 'Ingeniera en TIC especializada en desarrollo de apps avanzadas del software y soluciones empresariales.',
        hero_about_role: 'ING. EN TICS // DESARROLLO DE SOFTWARE AVANZADO',
        about_title: 'BIO_PERSPECTIVA',
        about_desc: 'Soy Ingeniera en Tecnologías de la Información y Comunicación con especialidad en Desarrollo de Aplicaciones Avanzadas del Software, enfocada en crear soluciones tecnológicas integrales, con experiencia en el ciclo de vida completo de desarrollo. Mi perspectiva técnica abarca desde la creación de aplicaciones móviles nativas de alto rendimiento hasta la implementación de complejos sistemas empresariales SAP, priorizando siempre la eficiencia, la escapabilidad y una arquitectura de software impecable.',
        exp_title: 'REGISTROS_EJECUCIÓN',
        projects_title: 'ÍNDICE_NÚCLEO',
        certs_title: 'DIPLOMAS_VERIFICADOS',
        contact_title: 'PROTOCOLOS_TRANSMISIÓN',
        cv_standard: 'CV_ESTÁNDAR',
        cv_ai: 'CV_ESPECIALIZADO',
        hero_btn_projects: 'VER PROYECTOS',
        hero_btn_contact: 'CONTACTO',
        cat_all: "Todos",
        cat_front: "Frontend",
        cat_back: "Backend",
        cat_completo: "Full-stack",
        cat_prototipo: "Prototipos",
        cat_empresarial: "Enterprise",
        exp_status: 'REGISTRO_CARRERA_V6.0',
        exp_ver: 'VERSIÓN_ESTABLE_2026',
        exp_node: 'NODO_0',
        exp_perspective: 'PERSPECTIVA_DEL_REGISTRO',
        exp_achievements: 'ARQUITECTURA_DE_LOGROS',
        exp_execution: 'EJECUCIÓN_ESTABLE',
        exp_prospection: 'PROSPECCIÓN_SISTEMA',
        exp_innovation: 'CONTINUANDO EL CAMINO_DE_INNOVACIÓN...',
        cert_vault: 'CREDENTIAL_VAULT',
        cert_creds: 'CREDENCIALES',
        cert_issued: 'EMITIDO',
        cert_view: 'VER',
        cat_enterprise: 'ENTERPRISE',
        cat_mobile: 'MOBILE',
        cat_web: 'WEB',
        cat_generic: 'GENÉRICO',
        repos_verified: 'REPOS_VERIFICADOS_OK',
        sync_protocol: 'PROTOCOLO_SINCRONIZACIÓN_GITHUB',
        sync_connected: 'CONECTADO_API_V3',
        sync_desc: 'ORQUESTACIÓN_NÚCLEO: Sistema de sincronización de alto rendimiento vinculado directamente a la API v3 de GitHub (Bearer Auth Enabled). Mediante el análisis dinámico de metadatos y estructuras de README, el motor orquestador interpreta automáticamente arquitecturas, stacks técnicos y retos de ingeniería, garantizando un índice tecnológico verificado y siempre vigente.',
        inspect: 'INSPECCIONAR',
        challenge_analysis: 'ANÁLISIS_RETO',
        solution_strategy: 'ESTRATEGIA_SOLUCIÓN',
        engineering_capabilities: 'CAPACIDADES_TÉCNICAS',
        stk_architecture: 'STK_ARCHITECTURE_MANIFEST',
        arch_notes: 'NOTAS_ARQUITECTURA',
        terminate_audit: 'FINALIZAR_INSPECCIÓN',
        sys_status: 'RUNLEVEL_5 // AUTH_OK',
        sys_root_menu: 'MENÚ_RAÍZ',
        sys_select_node: 'SELECCIONAR_NODO_OBJETIVO:',
        sys_encryption: 'ENCRIPTACIÓN_ACTIVA // AES-256',
        sys_ver: 'VER: 6.4.2 // SYSTM_UI OPTIMIZED',
        sys_runtime: 'TIEMPO_EJECUCIÓN: SESIÓN_ACTIVA'
    },
    en: {
        nav_home: 'KERNEL',
        nav_about: 'BIO',
        nav_exp: 'LOGS',
        nav_projects: 'CORE',
        nav_certs: 'HASH',
        nav_contact: 'IO',
        hero_status: 'RUNLEVEL_5: ACTIVE',
        hero_title: "ROOT@USER:",
        hero_role: 'SOFTWARE DEVELOPER // FULL STACK // MOBILE // SAP',
        hero_desc: 'ICT Engineer specialized in Advanced Software Application Development and enterprise solutions.',
        about_title: 'BIO_PERSPECTIVE',
        about_desc: 'I am an Information and Communication Technologies Engineer specialized in Advanced Software Application Development, focused on creating comprehensive technological solutions with experience in the complete development lifecycle. My technical perspective spans from high-performance native mobile apps to complex SAP enterprise systems, always prioritizing efficiency, scalability, and flawless software architecture.',
        hero_about_role: 'IT ENGINEER // ADVANCED SOFTWARE APP DEV',
        exp_title: 'EXECUTION_LOGS',
        projects_title: 'CORE_INDEX',
        certs_title: 'VERIFIED_DIPLOMAS',
        contact_title: 'TRANSMISSION_PROTOCOL',
        cv_standard: 'STANDARD_CV',
        cv_ai: 'SPECIALIZED_CV',
        hero_btn_projects: 'VIEW PROJECTS',
        hero_btn_contact: 'CONTACT',
        cat_all: "All",
        cat_front: "Frontend",
        cat_back: "Backend",
        cat_completo: "Full-stack",
        cat_prototipo: "Prototypes",
        cat_empresarial: "Enterprise",
        exp_status: 'CAREER_LOG_V6.0',
        exp_ver: 'STABLE_BUILD_2026',
        exp_node: 'NODE_0',
        exp_perspective: 'LOG_PERSPECTIVE',
        exp_achievements: 'ACHIEVEMENT_ARCHITECTURE',
        exp_execution: 'STABLE_EXECUTION',
        exp_prospection: 'SYSTEM_PROSPECTION',
        exp_innovation: 'CONTINUING THE INNOVATION_PATHWAY...',
        cert_vault: 'CREDENTIAL_VAULT',
        cert_creds: 'CREDENTIALS',
        cert_issued: 'ISSUED',
        cert_view: 'VIEW',
        cat_enterprise: 'ENTERPRISE',
        cat_mobile: 'MOBILE',
        cat_web: 'WEB',
        cat_generic: 'GENERIC',
        repos_verified: 'REPOS_VERIFIED_OK',
        sync_protocol: 'GITHUB_SYNC_PROTOCOL',
        sync_connected: 'API_V3_CONNECTED',
        sync_desc: "CORE_ORCHESTRATION: High-performance synchronization system directly linked to the GitHub API v3 (Bearer Auth Enabled). Through dynamic parsing of metadata and README structures, the orchestration engine automatically interprets architectures, technical stacks, and engineering challenges, ensuring a verified and always-current technical index.",
        inspect: 'INSPECT',
        challenge_analysis: 'CHALLENGE_ANALYSIS',
        solution_strategy: 'SOLUTION_STRATEGY',
        engineering_capabilities: 'ENGINEERING_CAPABILITIES',
        stk_architecture: 'STK_ARCHITECTURE_MANIFEST',
        arch_notes: 'ARCHITECTURE_NOTES',
        terminate_audit: 'TERMINATE_AUDIT',
        sys_status: 'RUNLEVEL_5 // AUTH_OK',
        sys_root_menu: 'ROOT_MENU',
        sys_select_node: 'SELECT_TARGET_NODE:',
        sys_encryption: 'ACTIVE_ENCRYPTION // AES-256',
        sys_ver: 'VER: 6.4.2 // SYSTM_UI OPTIMIZED',
        sys_runtime: 'RUNTIME: ACTIVE_SESSION'
    }
};
